### ISSUE TITLE
NSRecursiveLock to dispatch_sync

### ISSUE THREAD

**Issue by andr-ggn** [ChimeHQ/OperationPlus#11]
I think it is not good idea to use NSRecursiveLock for AsyncOperation, 
as I know - lock, unlock should call from a same thread. 
Your variant of implementation does not guarantee that.

What do you think about this?

**Comment by mattmassicotte** [comment]
Hello! Thanks for the question. You are right, this is a pretty subtle area.

I have used recursive locks very rarely, but this is a case where I *think* it is necessary. At issue is NSOperation/Queue's used of KVO, and managing state changes.

My concern with a non-recursive lock (like `dispatch_sync`), is the behavior within the `func transition(to newState: State)` function. I think it is extremely likely that NSOperationQueue will access state variables when those KVO notifications fire. Without a recursive lock, those reads will deadlock.

I will admit that I have not proved this is the case by stepping through with a debugger. But, this implementation is 100% safe in that case, even if the implementation changes across OS/platforms.

Did you run into a problem with this, or were you just looking at the code?
